##########
# Stages #
##########

variable "enabled" {
  type        = bool
  default     = true
  description = "A flag that indicates whether to create or decomission a resource. Set to True to create or False to decomission."
}

variable "rest_api_id" {
  type        = string
  description = "The ID of the REST API."
}

variable "stage_name" {
  type        = string
  description = "The name of the Stage."
}

variable "stage_description" {
  type        = string
  default     = ""
  description = "Description of the Stage."
}

variable "deployment_id" {
  type        = string
  description = "The ID of the API Gateway deployment."
}

variable "stage_variables" {
  type        = map(string)
  default     = {}
  description = "A map containing the Stage variables."
}

variable "cache_cluster_enabled" {
  type        = bool
  default     = false
  description = "A boolean flag to specify whether or not a Cache Cluster must be enabled for the Stage."
}

variable "xray_tracing_enabled" {
  type        = bool
  default     = true
  description = "A boolean flag to specify whether or not X-Ray Active Tracing must be enabled."
}

variable "cache_cluster_size" {
  type        = string
  default     = null
  description = "The size of the Cache Cluster for the Stage. Valid values are: 0.5, 1.6, 6.1, 13.5, 28.4, 58.2, 118 and 237"
}

variable "client_certificate_id" {
  type        = string
  default     = null
  description = "The client certificate ID for the Stage."
}

variable "documentation_version" {
  type        = string
  default     = null
  description = "The version of the associated API documentation."
}

###################
# Method Settings #
###################

variable "method_path" {
  type        = string
  default     = "*/*"
  description = "Specify the method path as {resource_path}/{http_method} to override an individual method, or */* to override all methods in a Stage."
}

variable "logging_level" {
  type        = string
  default     = "INFO"
  description = "The degree of detail captured in the logs generated by API Gateway. Valid values are: INFO, ERROR and OFF."
}

variable "metrics_enabled" {
  type        = bool
  default     = true
  description = "A boolean flag that specifies whether or not to enable CloudWatch Metrics for the Methods in the Stage."
}

variable "data_trace_enabled" {
  type        = bool
  default     = true
  description = "A boolean flag that specifies whether or not to enable Data Trace logging for the Methods in the Stage."
}

variable "burst_limit" {
  type        = number
  default     = 5000
  description = "The throttling burst limit."
}

variable "rate_limit" {
  type        = number
  default     = 10000
  description = "The throttling rate limit."
}
